id: P006665
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG13431
  title: རྔ་ཁུལ་ནང་བསྟན་གྲུབ་མཐའ་རིས་མེད་ཀྱི་དགོན་སྡེའི་མཚམས་སྦྱོར་སྙན་པའི་དུང་སྒྲ།
  author: ''
  volumes:
    e59bae31c44c4c7f8e8eb19550ff7587:
      image_group_id: I1KG13434
      title: ''
      volume_number: 1
      total_pages: 565
      base_file: v001.txt
